<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>LoanApi-Development-c6a758eb-6f37-44ec-91df-75ce0120bc78</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../LoanApi.Application/LoanApi.Application.csproj" />
    <ProjectReference Include="../LoanApi.Infrastructure/LoanApi.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
</Project>
