<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/LoanApi.Api/LoanApi.Api.csproj" />
    <ProjectReference Include="../../src/LoanApi.Infrastructure/LoanApi.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../database/schema.sql" Link="database/schema.sql" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../database/001_add_loan_soft_delete.sql" Link="database/001_add_loan_soft_delete.sql" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../database/002_add_integrity_constraints.sql" Link="database/002_add_integrity_constraints.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
